---
title: "Download and process COSMIC files"
author: "Jim Zhang"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    fig_caption: yes
---

```{r global_setup, include=FALSE}
knitr::opts_chunk$set(dpi=300, fig.pos="H", fig.width=8, fig.height=6, echo=FALSE, warning=FALSE, message=FALSE);

source_url<-"sftp-cancer.sanger.ac.uk/cosmic/grch38/cosmic/v75";
file_home<-paste(Sys.getenv('RCHIVE_HOME'), 'data/variant/public/cosmic/src', sep='/');
file_out<-paste(Sys.getenv('RCHIVE_HOME'), 'data/variant/public/cosmic/r', sep='/');
```

# Source

 - All source files were downloaded from: **`r source_url`**
 - Downloaded files were unziped and saved to: **`r file_home`** for further processing
 - Processed files were archived to: **`r file_out`**

```{r save_script, include=FALSE}
##############################################################################################################
tm<-strsplit(as.character(Sys.time()), ' ')[[1]][1];
fn0<-paste(Sys.getenv("RCHIVE_HOME"), '/source/script/update/variant/ProcessCosmic.Rmd', sep='');
fn1<-paste(Sys.getenv("RCHIVE_HOME"), '/source/script/update/variant/log/', tm, '_ProcessCosmic.Rmd' , sep='');
file.copy(fn0, fn1)

```
 _END OF DOCUMENT_